[features]
seeds = false
[programs.devnet]
custos = "KbFF6rsA1TTiA59ngcGKeT4grZnEagaMTRGhsHVqDSZ"
# [programs.mainnet]
# custos = "KbFF6rsA1TTiA59ngcGKeT4grZnEagaMTRGhsHVqDSZ"

[registry]
url = "https://anchor.projectserum.com"

[provider]
# cluster = "mainnet"
cluster = "devnet"
wallet = "./key.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
